# This file configures Replit's deployment features

run = "npm run dev"

hidden = [".config", "package-lock.json"]

[env]
NODE_ENV = "production"

[nix]
channel = "stable-22_11"

[deployment]
run = "cross-env NODE_ENV=production node dist/index.js"
deploymentTarget = "cloudrun"
build = ["npm", "run", "build"]
ignorePorts = false