# This file configures Replit's deployment features

run = "npm run dev"

hidden = [".config", "package-lock.json", "node_modules", ".git", "dist"]

[env]
NODE_ENV = "production"
PORT = "5000"

[nix]
channel = "stable-22_11"

[deployment]
run = "node dist/index.js"
deploymentTarget = "cloudrun"
build = ["npm", "install", "&&", "npm", "run", "build"]
ignorePorts = false