# This file configures Replit's deployment features

run = "npm run dev"

hidden = [".config", "package-lock.json", "node_modules", ".git", "dist"]

[env]
NODE_ENV = "production"
PORT = "5000"

[nix]
channel = "stable-22_11"

[deployment]
run = "node server/index.js"
deploymentTarget = "cloudrun"
build = ["npm", "install", "&&", "chmod +x build-for-deploy.sh", "&&", "./build-for-deploy.sh"]
ignorePorts = false